#!/bin/sh
# Generated by 'mxcli init'. COMMIT THIS FILE.
#
# Run by the Claude Code SessionStart hook to make a fresh (or reaped and
# re-cloned) session ready to work: fetch mxcli if the binary is missing, then
# cache MxBuild + the runtime and provision the local database.
#
# The mxcli binary is git-ignored (~85 MB), so after an idle reap it is NOT in
# the fresh clone — which is exactly why this script fetches it rather than
# skipping when it is absent.
#
# Pin a specific mxcli with MXCLI_TAG=vX.Y.Z (default: nightly).
set -e

MPR='MxcliDemo1.mpr'
TAG="${MXCLI_TAG:-nightly}"

if [ ! -x ./mxcli ]; then
  # Prefer a copy that is already on this machine. Some environments ship mxcli
  # pre-installed on PATH, and the bootstrap instructions have you delete the
  # hardlink 'mxcli new' left in the project — after which this guard could
  # never be satisfied by the PATH binary and re-downloaded ~85 MB on EVERY
  # fresh session, forever. (ako/ChipCoV1)
  #
  # Hardlink first because that is what 'mxcli new' does and it costs nothing;
  # fall back to a symlink across filesystems, then to a copy. Any of the three
  # leaves ./mxcli working, which is what the rest of this script and the
  # project's own CLAUDE.md assume.
  onpath=$(command -v mxcli 2>/dev/null || true)
  if [ -n "$onpath" ] && [ -x "$onpath" ]; then
    echo "mxcli found on PATH (${onpath}) — linking it in rather than downloading."
    ln -f "$onpath" ./mxcli 2>/dev/null ||
      ln -sf "$onpath" ./mxcli 2>/dev/null ||
      cp "$onpath" ./mxcli
    chmod +x ./mxcli 2>/dev/null || true
  fi
fi

if [ ! -x ./mxcli ]; then
  os=$(uname -s | tr 'A-Z' 'a-z')
  case "$(uname -m)" in
    x86_64|amd64) arch=amd64 ;;
    arm64|aarch64) arch=arm64 ;;
    *) arch=$(uname -m) ;;
  esac
  url="https://github.com/mendixlabs/mxcli/releases/download/${TAG}/mxcli-${os}-${arch}"
  echo "mxcli not found — downloading ${TAG} for ${os}/${arch}..."
  if ! curl -fsSL -o ./mxcli "$url"; then
    echo "Could not download mxcli from ${url}." >&2
    echo "Fetch it manually, or set MXCLI_TAG to a released version." >&2
    exit 1
  fi
  chmod +x ./mxcli
fi

# Keep .ai-context/skills/ in step with this binary. The skills are embedded in
# mxcli and written once by 'mxcli init', so upgrading the binary used to leave
# yesterday's guidance in place with no warning — and an agent reads stale
# guidance with the same confidence as current guidance. Quiet when already
# current; never fatal, since a skills refresh must not block the session.
./mxcli init --sync-skills . || true

exec ./mxcli run --local --setup --ensure-db -p "$MPR"
